### PR TITLE
[Helm] Added CRD variables

### PR DESCRIPTION
**Pull request by DazWilkin**
**What this PR does / why we need it**:

See: #200 

Makes Helm Chart Templates more general-purpose by refactoring constants.

**Special notes for your reviewer**:

Two areas for debate:

1. I went with simpler rather than more expressive for the variables. This doesn't constrain to the existing CRDs nor does it provide a mechanism to support multiple versions. But, for now, this should be sufficient.

```YAML
crds:
  group: akri.sh
  version: v0
```

2. For clarity I used `printf` to format `apiVersion` but you may prefer the alternative:

 `{{ printf "%s/%s" .Values.crds.group .Values.crds.version }}`

Rather than

`{{ .Values.crds.group }}/{{ .Values.crds.version }}`

**If applicable**:
- [ ] this PR contains documentation
- [ ] this PR contains unit tests
- [ ] added code adheres to standard Rust formatting (`cargo fmt`)
- [ ] code builds properly (`cargo build`)
- [ ] code is free of common mistakes (`cargo clippy`)
- [ ] all Akri tests succeed (`cargo test`)
- [ ] inline documentation builds (`cargo doc`)
- [ ] version has been updated appropriately (`./version.sh`)

### CODE REVIEW

**Comment by bfjelds** [comment]
this will require a change to version.sh as well

```sh
    YAML_FILES="$BASEDIR/deployment/helm/templates/debug-echo.yaml $BASEDIR/deployment/helm/templates/onvif.yaml $BASEDIR/deployment/helm/templates/udev.yaml $BASEDIR/deployment/helm/templates/opcua.yaml"
    YAML_VERSION_PATTERN="^apiVersion: akri.sh/"
    for YAML_FILE in $YAML_FILES
    do
        check_file_version "$YAML_FILE" "$YAML_VERSION_PATTERN" "$CRD_VERSION"
        if [ "$?" -eq "1" ]; then exit 1; fi
    done
```

will need to become something like (untested)

```sh
    HELM_VALUES="$BASEDIR/deployment/helm/values.yaml"
  group: akri.sh
  version: v0
    check_twoline_version "$HELM_VALUES" "group: akri.sh" "version: $CRD_VERSION"
    if [ "$?" -eq "1" ]; then exit 1; fi
```

and a similar change in the update section.

**Comment by DazWilkin** [comment]
The redoubtable `./version.sh` .... How can I test the changes to ensure a CRD bump and without breaking things?

+ artificially bump `version.txt` to `2.0.0`?
+ Is there a `./update.sh --dry-run` equivalent?

**Comment by bfjelds** [comment]
> The redoubtable `./version.sh` .... How can I test the changes to ensure a CRD bump and without breaking things?
> 
> * artificially bump `version.txt` to `2.0.0`?
> * Is there a `./update.sh --dry-run` equivalent?

there is no --dry-run equivalent.  good idea though.

it has been a while since i changed the script but if i remember correctly, run through and do `-u -p` (0.1.5 should become 0.1.6), `-u -n` (0.1.6 should become 0.2.0), `-u -m` (0.2.0 should become 1.0.0), `-c -s` (should work), then change version.txt and run `-c -s` (all checks should fail).  then when you're done testing, you should be able to set version.txt to what you want and then do `-u -s`.

**Comment by DazWilkin** [comment]
@bjfelds please sanity check https://github.com/deislabs/akri/pull/205/commits/a1f94797b2dfeb1a6813a36c5773346e378f9c98 for me please.

+ Eye-balling (!) existing changes continue to be OK
+ `./deployment/helm/values.yaml` property `crds.version` is bumped by a major version change

> **NOTE** `./version.sh -c -s` terminates on first failure so it's unclear whether *all* checks fail or just the first. If this isn't my mistake, perhaps an update to the script to continue through all tests?

Questions:

+ To confirm do you want me to bump versions (patch?) with this PR too?
+ Is there a documented protocol for version bumping (what changes trigger version bumps)?

**Comment by bfjelds** [comment]
the version.sh changes look good to my eye too ... the proof, as they say, is in the pudding though.  please do update the version with -u -p.

versioning is addressed in contributing.md ... not sure how clear or visible that is though.  feedback welcomed :)

**Review by bfjelds — APPROVED** [review]

**Review by kate-goldenring — APPROVED** [review]

**Pull request merged**
