### PR TITLE
End-to-End Demo for Google Compute Engine

### LINKED ISSUE #50: How to deploy akri to Google Compute Engine and DigitalOcean
Wrote a [post](https://pretired.dazwilkin.com/posts/201022/) summarizing how to deploy the akri end-to-end to both Google Compute Engine and DigitalOcean.

Hope it helps foster adoption of akri!

### PR DESCRIPTION
**Pull request by DazWilkin**
Fixes #50 

+ Instructions for Compute Engine
+ Reference instructions from existing End-to-End Demo document

### CODE REVIEW

**Comment by bfjelds** [comment]
very cool!

**Comment by kate-goldenring** [comment]
Sorry for the delay on reviewing this. We are in the process of getting a GCE account so we can easily verify changes made to this later.

**Review by kate-goldenring — APPROVED** [review]

**Comment by DazWilkin** [comment]
You're very welcome!

Thanks for taking the time to review!

**Comment by DazWilkin** [comment]
Awesome!

**Pull request merged**
