### PR TITLE
Various typos fixed on new OPCUA documentation

### PR DESCRIPTION
**Pull request by didier-durand**
Hi there,

Some fixes on new OPCUA pages

Signed-off-by: Didier Durand <durand.didier@gmail.com>

**What this PR does / why we need it**:

Improvements to new documentation

**Special notes for your reviewer**:

**If applicable**:
- [X] this PR contains documentation
- [ ] this PR contains unit tests
- [ ] added code adheres to standard Rust formatting (`cargo fmt`)
- [ ] code builds properly (`cargo build`)
- [ ] code is free of common mistakes (`cargo clippy`)
- [ ] all Akri tests succeed (`cargo test`)
- [ ] inline documentation builds (`cargo doc`)
- [ ] version has been updated appropriately (`./version.sh`)

### CODE REVIEW

**Comment by didier-durand** [comment]
Just added some additional fixes on extensibility.md

**Comment by bfjelds** [comment]
> Just added some additional fixes on extensibility.md

It is hard to see what the diffs are in github.com for your extensibility changes are (did the line endings change?)... the other files seem good.

**Comment by didier-durand** [comment]
@bfjelds : I fully agree with you. The diff is presented differently than it is usually. I am on MacOS (Linux convention for line ends): maybe the file was created on Windows? 
The "real" changes are still highlighted by Github's diff in lines 138, 206, 366, 463 and 663.
Best
Didier

**Review by kate-goldenring — APPROVED** [review]
Thanks for fixing these!

**Comment by kate-goldenring** [comment]
> @bfjelds : I fully agree with you. The diff is presented differently than it is usually. I am on MacOS (Linux convention for line ends): maybe the file was created on Windows?
> The "real" changes are still highlighted by Github's diff in lines 138, 206, 366, 463 and 663.
> Best
> Didier

If I open the PR using the GitHub VS Code extension, it only highlights those few lines.

**Comment by didier-durand** [comment]
@kate-goldenring and @bfjelds : the diff Eclipse also highlights only the lines that I mentioned. So, good to go. Didier

**Review by bfjelds — APPROVED** [review]

**Pull request merged**
