### PR TITLE
Upload code coverage to codecov [SAME VERSION]

### PR DESCRIPTION
**Pull request by bfjelds**
You can view the results of this PR here: https://codecov.io/gh/deislabs/akri/pulls

Eventually, when this gets merged down to main, there will be more info on https://codecov.io/gh/deislabs/akri.

### CODE REVIEW

**Comment by kate-goldenring** [comment]
Just understanding codecov: so will this beautiful coverage graph show up on all PRs that trigger the taurpalin check?

**Comment by bfjelds** [comment]
> Just understanding codecov: so will this beautiful coverage graph show up on all PRs that trigger the taurpalin check?

Apparently.  Do you hate it?

**Comment by kate-goldenring** [comment]
> > Just understanding codecov: so will this beautiful coverage graph show up on all PRs that trigger the taurpalin check?
> 
> Apparently. Do you hate it?

I think it is nice, but we should also give context on what Akri believe is good coverage. Or will it later show how the PR changes the coverage?

**Review by jiria — APPROVED** [review]

**Comment by bfjelds** [comment]
> > > Just understanding codecov: so will this beautiful coverage graph show up on all PRs that trigger the taurpalin check?
> > 
> > 
> > Apparently. Do you hate it?
> 
> I think it is nice, but we should also give context on what Akri believe is good coverage. Or will it later show how the PR changes the coverage?

I think that  coverage delta will show how this PR changed the coverage.

**Pull request merged**
