### PR TITLE
[Extensibility] HTTP protocol

### PR DESCRIPTION
**Pull request by DazWilkin**
**What this PR does / why we need it**:

Implements: #85 

**Special notes for your reviewer**:

**If applicable**:
- [X] this PR contains documentation
- [ ] this PR contains unit tests
- [X] added code adheres to standard Rust formatting (`cargo fmt`)
- [X] code builds properly (`cargo build`)
- [ ] code is free of common mistakes (`cargo clippy`)
- [ ] all Akri tests succeed (`cargo test`)
- [ ] inline documentation builds (`cargo doc`)
- [ ] version has been updated appropriately (`./version.sh`)

### CODE REVIEW

**Comment by bfjelds** [comment]
@DazWilkin, thanks so much for this!

I love this as a replacement for Nessie ... maybe where all of the code here goes into a `http-extensibility` branch (similar to the current `nessie` branch) and the doc changes go into `docs/extensibility.md` (with a link to the branch).

What do you think about that?

**Comment by DazWilkin** [comment]
@bfjelds Thank you!

I didn't intend it to replace -- but complement -- Nessie.

I very much value **all** feedback from the top (this isn't a good protocol) to the bottom (why don't you rename this variable).

I sent @kate-goldenring on Slack a link to something I wrote on the back of developing the http protocol, I'd be interested in (all of) your views on that too; I attempt to describe Akri in a slightly different way and hope it provides an outsider's perspective for your team.

Yes to the branch idea though I'll need help understanding how to undo the PR to main and moving it to `http-extensibility`.

**Comment by bfjelds** [comment]
For me, `nessie` is fun but contrived.  I'm hoping that `http` is closer to a real scenario and therefore more useful :)

We may need to create the branch for you to create the PR against,

**Comment by bfjelds** [comment]
I created `https://github.com/deislabs/akri/tree/http-extensibility` as an implementation branch for your code changes ... with the idea that you might move the code changes into a PR there and this can become a set of changes for extensibility.md.  How does that sound?

**Comment by DazWilkin** [comment]
Thanks @bfjelds.

How do I move the PR? Should I delete it and recreate it?

**Comment by bfjelds** [comment]
If it were me, I think I would do something like this:

**To create the new PR to http-extensibility**
1. git checkout -b my-http-extensibility
1. git rebase -i upstream/http-extensibility
1. `<sort out any merges>`
1. git push my-fork my-http-extensibility
1. `<use github.com to create new PR from my-http-extensibility to http-extensibility>`

**To change existing PR to a doc change to extensibility.md**
1. `<migrate extensibility-http.md to extensibility.md>`
1. git add extensibility.md
1. git commit -m "update extensibility.md to replace nessie"
1. git rebase -i upstream/main
1. `<drop all commits except the change you just made>`
1. git push -f `<your fork>` `<your branch name>`

**Comment by DazWilkin** [comment]
The first steps give me a `my-http-extensibility` branch in my fork (`DazWilkin/akri`) current with your `http-extensibility` but there will be no changes and thus no PR.

I understand `git mv` the `extensibility-http.md` --> `extensibility.md`

I'm unclear why|where I'm dropping (deleting?) commits?

Is the intent of the second section to effectively rename my forked branch? Am I pushing the commits from my existing branch to the new `my-http-extensibility` branch.

Would it be easier if we deleted my previous PR and I create another from my existing branch to `http-extensibility` (with the doc file renamed)?

**Comment by bfjelds** [comment]
my intent with the first steps was to start with DazWilkin:protocol-http and create a new branch (my-http-extensibility), then rebase it onto http-extensibility.  the end result should be moving all of these code changes into my-http-extensibility in a way that was easily mergable with http-extensibility with the PR.

the intent of the second set of steps was to modify this PR so that it only included md changes.  however that is accomplished easily for you is good for me :) ... we can update this PR or abandon it and start fresh, whatever works for you.

**Comment by DazWilkin** [comment]
Got it! Thanks for helping me understand

**Comment by bfjelds** [comment]
no problem ... I'm no git expert, so I apologize if I suggest something that is harder than it needs to be.

**Comment by DazWilkin** [comment]
PR https://github.com/deislabs/akri/pull/135 replaces the majority of the commits of this PR with `deislabs:http-extensibility`

**Comment by DazWilkin** [comment]
Ah, I think I inadvertently closed the PR by reverting all its commits.

I wanted to undo everything on the `DazWilkin:protocol-http` branch and then apply the `extensibility.md` rename.

Apologies.

**Pull request closed without merging**
