### PR TITLE
Simplify mockall usage

### PR DESCRIPTION
**Pull request by jiayihu**
**What this PR does / why we need it**:
Updating mockall to latest allows to remove warnings https://github.com/asomers/mockall/pull/124 and also suppoort `async_trait`.

Unfortunately, ideally the mocks should be generated only during tests but `cfg(test)` doesn't work across dependencies https://github.com/rust-lang/rust/issues/59168. In the following code, `MockSlotQuery` cannot be imported from another crate:

```rust
#[cfg(test)]
use mockall::{automock, predicate::*};

#[cfg_attr(test, automock)]
#[async_trait]
pub trait SlotQuery {
    async fn get_node_slots(&self) -> SlotQueryResult;
}
```

If `cfg(test)` worked across deps, `mockall` could also be listed as dev-dep:

```toml
[dev-dependencies]
mockall = "0.9.0"
```

However I think this is already the current behaviour and since actual tests are behind `#[cfg(test)]`, mocks are stripped in release build.

**Special notes for your reviewer**:

**If applicable**:
- [ ] this PR contains documentation
- [ ] this PR contains unit tests
- [ ] added code adheres to standard Rust formatting (`cargo fmt`)
- [x] code builds properly (`cargo build`)
- [ ] code is free of common mistakes (`cargo clippy`)
- [ ] all Akri tests succeed (`cargo test`)
- [ ] inline documentation builds (`cargo doc`)
- [x] version has been updated appropriately (`./version.sh`)

### CODE REVIEW

**Comment by bfjelds** [comment]
love, love, love the idea of this ... the async mockall code felt so hackish!

**Comment by bfjelds** [comment]
looks like `cargo fmt` needs to be run on the PR

**Comment by kate-goldenring** [comment]
Thanks for updating mockall! This is great. One more version update should do the trick.

**Comment by jiayihu** [comment]
Ready to go 🚀

**Review by bfjelds — APPROVED** [review]

**Pull request merged**
